### ISSUE TITLE
Version displayed as null

### ISSUE THREAD

**Issue by zachlayman-applitools** [yanirta/ImageTester#16]
![Screen Shot 2020-04-27 at 4 13 29 PM](https://user-images.githubusercontent.com/48330753/80421448-21b7e200-88a2-11ea-8c89-52d3c707d9bc.png)

1) Version of Image Tester is reported as null instead of 1.3.1
2) Can a -v or --version command be added to properly query the current version?

**Comment by yanirta** [comment]
Hey,
Resolved in version 1.4.14 (and on)
