### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by jankcat** [yanirta/ImageTester#3]
Hello,

It appears that there is a memory leak or similar. When uploading screenshots to Eyes using this tool, the tool's memory usage continues to grow with each screenshot uploaded.

![screen shot 2017-06-09 at 12 01 55 pm](https://user-images.githubusercontent.com/7744158/27091060-414fca18-501c-11e7-9f8b-f33c6dc718b4.png)

As you can see from that screenshot, after about 2-3 minutes of uploading (80-90 steps across 10~ tests), the memory usage has reached over 3GB. Moments later, the memory usage reached 3.5GB, which is the default maximum allowed by Java. 

I am assuming that the ImageStep.java class should either be disposed of, or just its img property be disposed/nulled, as the memory gains are likely related to the Image Data being held onto in RAM forever.

**Comment by jankcat** [comment]
@yanirta @LiranApplitools

**Comment by LiranApplitools** [comment]
Hey Jankcat,
Thanks for bringing into our attention - we are currently working on it and it will be fixed in future release.

Liran.

**Comment by yanirta** [comment]
The memory performance was improved in the last version (0.2.2)

VisualVM memmory consumption:
![screen shot 2017-06-21 at 12 15 24](https://user-images.githubusercontent.com/6667420/27377362-60c4bb26-567d-11e7-8596-5b1c9291c38b.png)

Note that the heap size includes objects that weren't GC'ed yet.

**Comment by yanirta** [comment]
The memory performance was improved in the last version (0.2.2)

VisualVM memmory consumption:
![screen shot 2017-06-21 at 12 15 24](https://user-images.githubusercontent.com/6667420/27377362-60c4bb26-567d-11e7-8596-5b1c9291c38b.png)

Note that the heap size includes objects that weren't GC'ed yet.

**Comment by jankcat** [comment]
It seems the fix has created other issues....
![screen shot 2017-06-21 at 10 47 13 am](https://user-images.githubusercontent.com/7744158/27396049-1e646faa-566f-11e7-93ee-7414665f556b.png)

The exact same run that worked before now gives me NullPointerExceptions...

**Comment by yanirta** [comment]
Hi Tim,
I just pushed the fix, will upload a new release in coulpe of minutes.
PS. Current failures should still generate valid results.

BR,
Yanir

**Comment by jankcat** [comment]
Oh okay, thanks. I will give the new build a try.

**Comment by jankcat** [comment]
![screen shot 2017-06-21 at 3 24 26 pm](https://user-images.githubusercontent.com/7744158/27407505-c7e63e52-5695-11e7-9d9a-4b0bcc6ecb9a.png)

Sweeet. Looking good. It consistently stays around 800mb-1gb.

**Comment by yanirta** [comment]
Happy to hear!
Thanks for the update Tim.

**Comment by jankcat** [comment]
Thanks for the quick response!
